<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.shibboleth</groupId>
        <artifactId>parent</artifactId>
        <version>17.0.2</version>
    </parent>

    <groupId>uk.org.iay.incommon</groupId>
    <artifactId>inc-mda</artifactId>
    <version>0.10.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>InCommon Aggregator Beans</name>
    <description>
        Metadata aggregator beans for the InCommon federation.
    </description>
    <inceptionYear>2017</inceptionYear>

    <properties>
        <mda.version>0.10.0-SNAPSHOT</mda.version>
        <shib-shared.version>9.0.0</shib-shared.version>
        <checkstyle.version>7.6</checkstyle.version>
    </properties>

    <dependencies>

        <!-- Compile dependencies -->

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>net.shibboleth.metadata</groupId>
            <artifactId>mda-framework</artifactId>
            <version>${mda.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-support</artifactId>
            <version>${shib-shared.version}</version>
        </dependency>

        <!-- Provided Dependencies -->

        <!-- Runtime dependencies -->

        <!-- Test dependencies -->

        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-spring</artifactId>
            <version>${shib-shared.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth.metadata</groupId>
            <artifactId>mda-framework</artifactId>
            <version>${mda.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-beans</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-context</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Managed Dependencies -->

    </dependencies>

    <build>

        <plugins>

            <!--
                Checkstyle configuration for checkstyle:* goals called directly
                from the command line.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <configuration>
                    <configLocation>${checkstyle.configLocation}</configLocation>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <dependencies>
                    <!-- add optional Markdown processor -->
                    <dependency>
                        <groupId>org.apache.maven.doxia</groupId>
                        <artifactId>doxia-module-markdown</artifactId>
                        <version>1.7</version>
                    </dependency>
                    <!-- support DAV protocol for site deploy -->
                    <dependency>
                        <groupId>org.apache.maven.wagon</groupId>
                        <artifactId>wagon-webdav-jackrabbit</artifactId>
                        <version>2.10</version>
                    </dependency>
                </dependencies>
            </plugin>

        </plugins>

    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${checkstyle-plugin.version}</version>
                <configuration>
                    <configLocation>${checkstyle.configLocation}</configLocation>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <profiles>
        <profile>
            <id>lint</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <showDeprecation>true</showDeprecation>
                            <showWarnings>true</showWarnings>
                            <debug>true</debug>
                            <compilerArgument>-Xlint:unchecked</compilerArgument>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>shib-release</id>
            <url>https://build.shibboleth.net/nexus/content/groups/public</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>shib-snapshot</id>
            <url>https://build.shibboleth.net/nexus/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

    <scm>
        <connection>scm:git:https://gitlab.iay.org.uk/incommon/inc-mda.git</connection>
        <developerConnection>scm:git:ssh:git@gitlab.iay.org.uk:incommon/inc-mda.git</developerConnection>
        <url>https://gitlab.iay.org.uk/incommon/inc-mda</url>
    </scm>

    <developers>
        <developer>
            <id>iay</id>
            <name>Ian Young</name>
            <organizationUrl>http://iay.org.uk/</organizationUrl>
            <timezone>0</timezone>
        </developer>
    </developers>

    <distributionManagement>
        <repository>
            <id>iay-release</id>
            <url>https://apps.iay.org.uk/nexus/content/repositories/releases</url>
        </repository>
        <snapshotRepository>
            <id>iay-snapshot</id>
            <url>https://apps.iay.org.uk/nexus/content/repositories/snapshots</url>
        </snapshotRepository>
        <site>
            <id>iay-site</id>
            <url>dav:https://apps.iay.org.uk/nexus/content/sites/site/${project.artifactId}/${project.version}/</url>
        </site>
    </distributionManagement>

</project>
